### ISSUE TITLE
We Prefer To Get Property by Name

### ISSUE THREAD

**Issue by skaranuh** [connio/octopus-issues#153]
Hi,

We prefer to get profile properties by name like the other entities (profile, device). 
We have also created some builtin properties for our base profile and we prefer to retrieve them by name.

At the moment only id is supported.
http://docs.connio.com/v3/reference#view-api-client-details

If provided, we can reach property via its profile as below as in Connio v2:
/deviceprofiles/<profileName>/Properties/<propertyName>
or something like below:
/properties/<profileName$propertyName>

**Comment by bmrb** [comment]
Part of v3.1
