### ISSUE TITLE
Connio v3.1 - Incompatibility - Device profile is not created with empty tag array unlike connio v.3

### ISSUE THREAD

**Issue by skaranuh** [connio/octopus-issues#177]
Hi,

Connio v3.1 - Device profile is not created with empty tag array unlike connio v.3.

[{"code":"TagListEmpty","cause":"Tag list cannot be empty","message":"You can remove the `tags` field by setting to `null`.","moreInfoUrl":"https://docs.connio.com/errors/taglistempty"}] 

Previously, empty array was allowed in connio v3.

We need connio v3.1 to be backward compatible with connio v.3

**Comment by bmrb** [comment]
Can we close this issue?
