### ISSUE TITLE
Connio v3.1 - Incompatibility -Streamed datapoint schame differs from Connio v.3

### ISSUE THREAD

**Issue by skaranuh** [connio/octopus-issues#178]
We need the same datapoint schema with  connio v3.

Connio v.3.1 point schema:
{
  "_id": "7624490a83ddf3dc7823dfcd3c5fbc66",
  "_rev": "1-eb91d8f1783d14ae179af24f644fe020",
  "source": {
    "object": {
      "id": "_dev_330699328117777158",
      "name": "dev_330699328117777158"
    },
    "apiKeyId": "_key_330699328119061304",
    "protocol": "mqtt"
  },
  "feedId": "1a67b9c6-febc-48c3-86e3-f9190c826316",
  "annotations": {
    "prop": "current1"
  },
  "app": {
    "id": "_app_399210517662711311",
    "name": "ttamp"
  },
  "account": {
    "id": "_acc_399210441694392430",
    "name": "ttamp"
  },
  "serverTime": "2018-07-09T10:10:52.277Z",
  "sourceTime": "2018-07-09T13:10:16.083+03:00",
  "destination": {
    "object": {
      "id": "_dev_330699328117777158",
      "name": "dev_330699328117777158"
    },
    "property": {
      "id": "_prp_399210515421775612",
      "name": "current1"
    }
  },
  "value": 0
}

Connio v.3 datapoint schema:

{
  "_id": "3ed143fa0f22652b617b5adfe643b29f",
  "_rev": "1-729f22e09df0e70d5e14e886f22951f7",
  "source": {
    "object": {
      "id": "_dev_330699604640460339",
      "name": "dev_330699604640460339",
      "ownerId": ""
    },
    "protocol": "mqtt",
    "apiKeyId": "_key_330699604636338268"
  },
  "location": {
    **"zone": "22609068-130e-4e67-9697-7960ba27bd4e"**
  },
  "feedId": "33902a17-6f65-4462-9c77-a5cb62bd3c52",
  **"tags": [
    "envxthresholds",
    "Aydınlatma_Planı",
    "Sahadan_Parmak_İzlerini_Topla",
    "4_Numaralı_Aydınlatma",
    "Cihaz_Upgrade",
    "Device_LastIn",
    "Aydınlatma_Durumu",
    "Gateway_Durum_Sorgula",
    "Personel_Giriş-_Çıkış_Kaydı",
    "ConnectedDevice_ConnectionInfo",
    "Device_Active",
    "Cihaz_Log",
    "1_Numaralı_Aydınlatma",
    "3_Numaralı_Aydınlatma",
    "Cihaz_Konfigurasyon",
    "ConnectedDevice_ConnectionStatus",
    "2_Numaralı_Aydınlatma",
    "Parmak_İzi_Kaydı",
    "Cihaz_Bilgisi",
    "Cihazi_Yeniden_Başlat",
    "Parmak_İzlerini_Dağıt",
    "Cihaz_Online_Durumu",
    "Device_LastOut"
  ],**
  **"annotations": {
    "mac": "a0:6e:50:00:02:d7",
    "deviceProfileName": "uzden",
    "class": "CopernicusEnvironmentDevice",
    "prop": "current1",
    "vendor": "Kiosk",
    "product": "Spectrum"
  },**
  "app": {
    "id": "_app_337476150674375068",
    "name": "ttamp",
    "ownerId": ""
  },
  "account": {
    "id": "_acc_318415952022752527",
    "name": "ttamp",
    "ownerId": ""
  },
  "serverTime": "2018-07-05T23:40:20.874Z",
  "sourceTime": "2018-07-06T02:40:18.014+03:00",
  "destination": {
    "object": {
      "id": "_dev_330699604640460339",
      "name": "dev_330699604640460339",
      "ownerId": ""
    },
    "property": {
      "id": "_prp_328702648397941445",
      "name": "current1",
      "ownerId": "_dpf_328696070100105193"
    }
  },
  "value": 0
}

We need connio v3.1 to be backward compatible with connio v.3

**Comment by bmrb** [comment]
Closing since this has been worked on.
