### ISSUE TITLE
Connio v3.1 - Datapoints should be restreamed to couchdb from data low interruption(friday) to datapoint schema fix

### ISSUE THREAD

**Issue by skaranuh** [connio/octopus-issues#180]
Hi,

We need datapoints to be streamed to couchdb from data flow interruption (2018-07-06 04:58:55.000+03:00) to the time when datapoint scheme is fixed (Issue 178) and onwards by enabling dataconnector on issue 176.

**Comment by bmrb** [comment]
This is completed into a external couchDB. If you still need this data let me know. Otherwise feel free to close this issue.

**Comment by bmrb** [comment]
Closing.
