### ISSUE TITLE
IDC Prod Connio v3 rest endpoint is not working

### ISSUE THREAD

**Issue by skaranuh** [connio/octopus-issues#182]
Hi,

IDC Prod Connio v3 rest endpoint is not working.

Can you please check?

**Comment by skaranuh** [comment]
sample url:
https://api3.inv.connio.net/v3/devices

**Comment by skaranuh** [comment]
received eror is as below:

<html>
    <head>
        <title>502 Bad Gateway</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>502 Bad Gateway</h1>
        </center>
        <hr>
        <center>nginx</center>
    </body>
</html>

**Comment by bmrb** [comment]
This issue has been fixed.
