### ISSUE TITLE
Can not get provision response

### ISSUE THREAD

**Issue by asc793** [connio/octopus-issues#189]
I have tried to simulate provisionning operation as below and I have expected to get response from topic "connio/provisions/{clientId}".
I could observed that my message reflected to "connio/provisions/bridge" topic but couldn't  get anything from "connio/provisions/_???_1231231231".
Could you check it out please? 

Account : _acc_495269316522393674
Key : _key_495269325625889848
Secret : c5c864117881405fa8e9c7ec8cf3ece0

- create device
```
b5:f4:ac:c4:ee:f2
_dev_495372656871738527
```
- create an apiclient for provisionning
```
_api_495361017712321855
_key_495361017715314090
bf08c3181ab34af58c9b9df58cb2b948
```
- connect to broker with provisionning apiclients credentials
```
172.26.41.102
_???_1231231231
_key_495361017715314090
bf08c3181ab34af58c9b9df58cb2b948
```
- publish message as 
```
connio/provisions
{"cidType": "mac","cid": "b5:f4:ac:c4:ee:f2","configProperty": "configprop"}
```

**Comment by bmrb** [comment]
One common mistake is to forget plugging in this device to the app that facilitates the provisioning. Did you do that?

Also please make sure that `configprop` property  exists.

**Comment by asc793** [comment]
Ok, I have plugged in the device to an app and got the provision respose.

You can close this issue.
Thank you.
