### ISSUE TITLE
Can not set retention condition when type is mostrecent

### ISSUE THREAD

**Issue by asc793** [connio/octopus-issues#199]
Can not set retention condition when type is mostrecent.

I have posted object like below
`{"ownerId":"_dpf_499030749279893421","name":"R5pwzg9Kjj","type":"number","access":"public","publish":"always","retention":{"context":{"type":"default"},"type":"mostrecent","condition":{"when":"changed"}}}`

but object that created like below
`{"id":"_prp_499030754263056713","accountId":"_acc_498348052297733210","ownerId":"_dpf_499030749279893421","name":"R5pwzg9Kjj","friendlyName":"R5pwzg9Kjj","inherited":false,"qualifiedName":"eb0e51oj1k$r5pwzg9kjj","type":"number","access":"public","publish":"always","retention":{"context":{"type":"default"},"type":"mostrecent"},"locked":false,"dateCreated":"2018-11-20T12:45:01.679Z","dateModified":"2018-11-20T12:45:01.679Z"}`

Could you check it out please?

**Comment by bmrb** [comment]
Most recent types do not have retention policy since retention is about storing a property value.

**Comment by asc793** [comment]
Document says condition used when type is historical or mostrecent to indicate when the value will be stored... 
Could you check it out please?
https://docs.connio.com/v3/reference#section-retention-policy

**Comment by bmrb** [comment]
You are 100% right. This is very misleading. Going to update the documentation.

**Comment by bmrb** [comment]
Documentation is corrected. Thanks for careful reading.

**Comment by asc793** [comment]
Ok, you can close this issue.
Thank you.
