### ISSUE TITLE
InvalidAlertConditionExpression - eq operator with string value

### ISSUE THREAD

**Issue by cankut** [connio/octopus-issues#201]
I'm trying to:

1. Define a method on some custom profile (derived from Device built-in profile)
2. Set an Alert for one of the properties of this custom profile ("active" property inherited from Device built-in profile)
3. Alert's only handler will call the method mentioned in step 1.

However, I can't create Alert object with following request:

```
{
  "conditions": [
    {
      "severity": "warning",
      "expression": {
        "operation": "eq",
        "value": "inactive"
      },
      "handlers": [
        {
          "key": "H1",
          "notification": "callmethod",
          "timeout": "1 minute"
        }
      ]
    }
  ],
  "notifications": [
    {
      "name": "callmethod",
      "action": "method",
      "method": "_mtd_499595374257805041",
      "parameter": "myparam"
    }
  ],
  "name": "ActiveAlert",
  "friendlyName": "ActiveAlert",
  "ownerId": "_dpf_499595373335010698",
  "trigger": "active",
  "ttl": "500 seconds",
  "status": "enabled",
  "metric": "value"
}

```

It makes sense to me that I should set the expression as below, because

* I want to monitor changes in "active" property of Device built-in profile
* I want to raise the alert when "active" property has the value "inactive"

```
 {
        "operation": "eq",
        "value": "inactive"
}
```

Got this error;

```
{
  "code": "InvalidAlertConditionExpression",
  "cause": "Invalid alert expression: equals expression only accept numerical or boolean values",
  "message": "Provided alert condition expression cannot be interpreted. Please see API documentation for acceptable alert condition expressions.",
  "moreInfoUrl": "https://docs.connio.com/errors/invalidalertconditionexpression"
}
```

**Comment by bmrb** [comment]
try `match` with enums.

**Comment by cankut** [comment]
@bmrb Thanks, "match" works.

```
...
"notifications": [
	{
    "name": "Method-Notif-Sample",
    "action": "method",
    "method": "_mtd_392727204042600572",
    "parameter": "off"
  }
]
...
```

for method call notifications, in regard to "**parameter**", can we use javascript objects instead of string?

**Comment by bmrb** [comment]
Not sure but it should work. @jcroig might answer that better but he is on vacation. Best way is to try I guess.

**Comment by cankut** [comment]
@bmrb 

It works and not works at the same time (must be quantum effect 😄 )

works for a static object like 
`{name: "test"}`

not works for an object containing placeholder
`{name: "${value}"}`

see the reflected device state value:

 ```
{
        "mostRecent": {
          "x": {
            "Name": "${value}",
            "Age": 34
          }
        }
```

I am not sure what to expect here. Can you elaborate documentation on this ?

* different usage examples of "parameter" in notification object
* available placeholders that can be used inside "parameter"

etc.

**Comment by bmrb** [comment]
Right, I don't think the system searches/replaces variables inside the objects. Interesting case for sure. 

Can you provide it just as ${value} and make the conversion in the method instead?

Noted, we will improve the documentation.

**Comment by cankut** [comment]
> 
> Can you provide it just as ${value} and make the conversion in the method instead?
> 

Sure, thanks!
