### ISSUE TITLE
Written data over api does not reflect over mqtt

### ISSUE THREAD

**Issue by asc793** [connio/octopus-issues#206]
When I write data on a property over api, it should be reflected over mqtt.
Api accepts data but there is nothing on mqtt.

I have posted data to device;
/v3/data/devices/_dev_513559888236666723/properties/envxconfig
```
{
  "dps": [ 
    { "t": "2017-05-01T14:00:17.799Z", "v": {
                    "lightswitchmodetimeout": 600002,
                    "temphumidityinterval": 600000,
                    "zonedeltastart": 0,
                    "gmttimezone": 3,
                    "zonedeltaend": 0,
                    "timeserverip": 1956335538,
                    "currentinterval": 600000
                } }
  ]
}
```
with credentials;
_key_513559459371267921
5f642b5f346d4159bc4117f6f3a0f34b

I have connected to all mqtt brokers (172.26.41.102,172.26.41.103,172.26.41.104) and had listened root topic (connio/#) but nothing had appeared

**Comment by bmrb** [comment]
This is not the right way to test device mirroring. `connio/#` is for debugging not for testing and under normal circumstance you should not have access to it.

Please see documentation for how device mirroring is working; and test accordingly.

In a nutshell, you will need an app and API Client to listen this app.

**Comment by skaranuh** [comment]
“Sending Device Command” section does not include this breaking change. The document should be updated accordingly.

**Comment by bmrb** [comment]
> “Sending Device Commands” section does not include this breaking change. The document should be updated accordingly.

Noted. Will do.

**Comment by bmrb** [comment]
Done. closing.
